from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import DoctorProfileViewSet

router = DefaultRouter()
router.register(r'doctor', DoctorProfileViewSet, basename='doctor')

# Generate URL patterns for the viewset
urlpatterns = [
    # URL pattern for listing all doctors
    path('doctors/', DoctorProfileViewSet.as_view({'get': 'list'})),

    # URL pattern for retrieving a single doctor's profile
    path('doctor-profile/<int:pk>/', DoctorProfileViewSet.as_view({'get': 'retrieve'})),
    
    path('specialization/<str:specialization>/', DoctorProfileViewSet.as_view({'get': 'get_doctors_by_specialty'})),

    path('register/', DoctorProfileViewSet.as_view({'post': 'create'})),
   path('delete/<int:pk>/', DoctorProfileViewSet.as_view({'delete': 'destroy'})),

    # path('doctor-profile/<int:pk>/', DoctorProfileViewSet.as_view({'get': 'retrieve'})),
    # path('doctor-profile/<int:pk>/', DoctorProfileViewSet.as_view({'get': 'retrieve'})),

]

# Append the URLs generated by the router
urlpatterns += router.urls