from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import PostViewSet

router = DefaultRouter()
router.register(r'post', PostViewSet, basename='post')

# Generate URL patterns for the viewset
urlpatterns = [
    # URL pattern for listing all doctors
    path('posts/', PostViewSet.as_view({'get': 'list'})),

    # URL pattern for retrieving a single doctor's profile
    path('post-details/<int:pk>/', PostViewSet.as_view({'get': 'retrieve'})),
    
    path('get-posts-by-category/<str:category>/', PostViewSet.as_view({'get': 'get-posts-by-category'})),

    path('create-post/', PostViewSet.as_view({'post': 'create'})),
    path('delete/<int:pk>/', PostViewSet.as_view({'delete': 'destroy'})),

]

# Append the URLs generated by the router
urlpatterns += router.urls